#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - unattended-upgrades
  - htop
  - iotop
  - jq

runcmd:
  - echo "docker system prune --force" > /etc/cron.hourly/docker-cleanup.cron
  - rm -rf /etc/update-motd.d/99-one-click
  - ufw allow ssh
  - ufw allow dns
  - ufw allow ntp
  - ufw allow https
  - ufw allow http
  - ufw allow 2376/tcp
  - ufw allow 2377/tcp
  - ufw allow 7946/tcp
  - ufw allow 7946/udp
  - ufw allow 4789/udp
  - ufw reload
  - ufw --force enable
  - systemctl restart docker
